  
  
|[wx.adv.AnimationCtrl](https://docs.wxpython.org/wx.adv.AnimationCtrl.html)|![](https://docs.wxpython.org/_static/images/widgets/fullsize/wxmsw/wx.adv.animationctrl.png)|
|[wx.adv.BitmapComboBox](https://docs.wxpython.org/wx.adv.BitmapComboBox.html)|![](https://docs.wxpython.org/_static/images/widgets/fullsize/wxmac/wx.adv.bitmapcombobox.png)|
|[wx.adv.CalendarCtrl](https://docs.wxpython.org/wx.adv.CalendarCtrl.html)|![](https://docs.wxpython.org/_static/images/widgets/fullsize/wxmsw/wx.adv.calendarctrl.png)|
|[wx.adv.CommandLinkButton](https://docs.wxpython.org/wx.adv.CommandLinkButton.html)|![](https://docs.wxpython.org/_static/images/widgets/fullsize/wxmsw/wx.adv.commandlinkbutton.png)|
|[wx.adv.DatePickerCtrl](https://docs.wxpython.org/wx.adv.DatePickerCtrl.html)|![](https://docs.wxpython.org/_static/images/widgets/fullsize/wxmac/wx.adv.datepickerctrl.png)|
|[wx.adv.HyperlinkCtrl](https://docs.wxpython.org/wx.adv.HyperlinkCtrl.html)|![](https://docs.wxpython.org/_static/images/widgets/fullsize/wxmac/wx.adv.hyperlinkctrl.png)|
|[wx.adv.OwnerDrawnComboBox](https://docs.wxpython.org/wx.adv.OwnerDrawnComboBox.html)|![](https://docs.wxpython.org/_static/images/widgets/fullsize/wxgtk/wx.adv.ownerdrawncombobox.png)|
|[wx.adv.RichToolTip](https://docs.wxpython.org/wx.adv.RichToolTip.html)|![](https://docs.wxpython.org/_static/images/widgets/fullsize/wxmsw/wx.adv.richtooltip.png)|
|[wx.adv.TimePickerCtrl](https://docs.wxpython.org/wx.adv.TimePickerCtrl.html)|![](https://docs.wxpython.org/_static/images/widgets/fullsize/wxmac/wx.adv.timepickerctrl.png)|
|[wx.aui.AuiMDIParentFrame](https://docs.wxpython.org/wx.aui.AuiMDIParentFrame.html)|![](https://docs.wxpython.org/_static/images/widgets/fullsize/wxmsw/wx.aui.auimdiparentframe.png)|
|[wx.BitmapButton](https://docs.wxpython.org/wx.BitmapButton.html)|![](https://docs.wxpython.org/_static/images/widgets/fullsize/wxgtk/wx.bitmapbutton.png)|
|[wx.Button](https://docs.wxpython.org/wx.Button.html)|![](https://docs.wxpython.org/_static/images/widgets/fullsize/wxmsw/wx.button.png)|
|[wx.CheckBox](https://docs.wxpython.org/wx.CheckBox.html)|![](https://docs.wxpython.org/_static/images/widgets/fullsize/wxmac/wx.checkbox.png)|
|[wx.CheckListBox](https://docs.wxpython.org/wx.CheckListBox.html)|![](https://docs.wxpython.org/_static/images/widgets/fullsize/wxmac/wx.checklistbox.png)|
|[wx.Choice](https://docs.wxpython.org/wx.Choice.html)|![](https://docs.wxpython.org/_static/images/widgets/fullsize/wxgtk/wx.choice.png)|
|[wx.Choicebook](https://docs.wxpython.org/wx.Choicebook.html)|![](https://docs.wxpython.org/_static/images/widgets/fullsize/wxmsw/wx.choicebook.png)|
|[wx.CollapsiblePane](https://docs.wxpython.org/wx.CollapsiblePane.html)|![](https://docs.wxpython.org/_static/images/widgets/fullsize/wxgtk/wx.collapsiblepane.png)|
|[wx.ColourPickerCtrl](https://docs.wxpython.org/wx.ColourPickerCtrl.html)|![](https://docs.wxpython.org/_static/images/widgets/fullsize/wxgtk/wx.colourpickerctrl.png)|
|[wx.ComboBox](https://docs.wxpython.org/wx.ComboBox.html)|![](https://docs.wxpython.org/_static/images/widgets/fullsize/wxmsw/wx.combobox.png)|
|[wx.ComboCtrl](https://docs.wxpython.org/wx.ComboCtrl.html)|![](https://docs.wxpython.org/_static/images/widgets/fullsize/wxmsw/wx.comboctrl.png)|
|[wx.dataview.DataViewCtrl](https://docs.wxpython.org/wx.dataview.DataViewCtrl.html)|![](https://docs.wxpython.org/_static/images/widgets/fullsize/wxmsw/wx.dataview.dataviewctrl.png)|
|[wx.dataview.DataViewTreeCtrl](https://docs.wxpython.org/wx.dataview.DataViewTreeCtrl.html)|![](https://docs.wxpython.org/_static/images/widgets/fullsize/wxgtk/wx.dataview.dataviewtreectrl.png)|
|[wx.Dialog](https://docs.wxpython.org/wx.Dialog.html)|![](https://docs.wxpython.org/_static/images/widgets/fullsize/wxgtk/wx.dialog.png)|
|[wx.DirPickerCtrl](https://docs.wxpython.org/wx.DirPickerCtrl.html)|![](https://docs.wxpython.org/_static/images/widgets/fullsize/wxmac/wx.dirpickerctrl.png)|
|[wx.FileCtrl](https://docs.wxpython.org/wx.FileCtrl.html)|![](https://docs.wxpython.org/_static/images/widgets/fullsize/wxgtk/wx.filectrl.png)|
|[wx.FilePickerCtrl](https://docs.wxpython.org/wx.FilePickerCtrl.html)|![](https://docs.wxpython.org/_static/images/widgets/fullsize/wxgtk/wx.filepickerctrl.png)|
|[wx.FontPickerCtrl](https://docs.wxpython.org/wx.FontPickerCtrl.html)|![](https://docs.wxpython.org/_static/images/widgets/fullsize/wxmac/wx.fontpickerctrl.png)|
|[wx.Frame](https://docs.wxpython.org/wx.Frame.html)|![](https://docs.wxpython.org/_static/images/widgets/fullsize/wxgtk/wx.frame.png)|
|[wx.Gauge](https://docs.wxpython.org/wx.Gauge.html)|![](https://docs.wxpython.org/_static/images/widgets/fullsize/wxmac/wx.gauge.png)|
|[wx.GenericDirCtrl](https://docs.wxpython.org/wx.GenericDirCtrl.html)|![](https://docs.wxpython.org/_static/images/widgets/fullsize/wxmac/wx.genericdirctrl.png)|
|[wx.lib.agw.advancedsplash.AdvancedSplash](https://docs.wxpython.org/wx.lib.agw.advancedsplash.AdvancedSplash.html)|![](https://docs.wxpython.org/_static/images/widgets/fullsize/wxmsw/wx.lib.agw.advancedsplash.advancedsplash.png)|
|[wx.lib.agw.aquabutton.AquaButton](https://docs.wxpython.org/wx.lib.agw.aquabutton.AquaButton.html)|![](https://docs.wxpython.org/_static/images/widgets/fullsize/wxmsw/wx.lib.agw.aquabutton.aquabutton.png)|
|[wx.lib.agw.aui.auibar.AuiToolBar](https://docs.wxpython.org/wx.lib.agw.aui.auibar.AuiToolBar.html)|![](https://docs.wxpython.org/_static/images/widgets/fullsize/wxmsw/wx.lib.agw.aui.auibar.auitoolbar.png)|
|[wx.lib.agw.aui.auibook.AuiNotebook](https://docs.wxpython.org/wx.lib.agw.aui.auibook.AuiNotebook.html)|![](https://docs.wxpython.org/_static/images/widgets/fullsize/wxmsw/wx.lib.agw.aui.auibook.auinotebook.png)|
|[wx.lib.agw.aui.framemanager.AuiManager](https://docs.wxpython.org/wx.lib.agw.aui.framemanager.AuiManager.html)|![](https://docs.wxpython.org/_static/images/widgets/fullsize/wxmsw/wx.lib.agw.aui.framemanager.auimanager.png)|
|[wx.lib.agw.balloontip.BalloonTip](https://docs.wxpython.org/wx.lib.agw.balloontip.BalloonTip.html)|![](https://docs.wxpython.org/_static/images/widgets/fullsize/wxmsw/wx.lib.agw.balloontip.balloontip.png)|
|[wx.lib.agw.buttonpanel.ButtonPanel](https://docs.wxpython.org/wx.lib.agw.buttonpanel.ButtonPanel.html)|![](https://docs.wxpython.org/_static/images/widgets/fullsize/wxmsw/wx.lib.agw.buttonpanel.buttonpanel.png)|
|[wx.lib.agw.cubecolourdialog.CubeColourDialog](https://docs.wxpython.org/wx.lib.agw.cubecolourdialog.CubeColourDialog.html)|![](https://docs.wxpython.org/_static/images/widgets/fullsize/wxgtk/wx.lib.agw.cubecolourdialog.cubecolourdialog.png)|
|[wx.lib.agw.customtreectrl.CustomTreeCtrl](https://docs.wxpython.org/wx.lib.agw.customtreectrl.CustomTreeCtrl.html)|![](https://docs.wxpython.org/_static/images/widgets/fullsize/wxgtk/wx.lib.agw.customtreectrl.customtreectrl.png)|
|[wx.lib.agw.flatmenu.FlatMenuBar](https://docs.wxpython.org/wx.lib.agw.flatmenu.FlatMenuBar.html)|![](https://docs.wxpython.org/_static/images/widgets/fullsize/wxmsw/wx.lib.agw.flatmenu.flatmenubar.png)|
|[wx.lib.agw.flatnotebook.FlatNotebook](https://docs.wxpython.org/wx.lib.agw.flatnotebook.FlatNotebook.html)|![](https://docs.wxpython.org/_static/images/widgets/fullsize/wxmsw/wx.lib.agw.flatnotebook.flatnotebook.png)|
|[wx.lib.agw.floatspin.FloatSpin](https://docs.wxpython.org/wx.lib.agw.floatspin.FloatSpin.html)|![](https://docs.wxpython.org/_static/images/widgets/fullsize/wxmsw/wx.lib.agw.floatspin.floatspin.png)|
|[wx.lib.agw.fmcustomizedlg.FMCustomizeDlg](https://docs.wxpython.org/wx.lib.agw.fmcustomizedlg.FMCustomizeDlg.html)|![](https://docs.wxpython.org/_static/images/widgets/fullsize/wxmsw/wx.lib.agw.fmcustomizedlg.fmcustomizedlg.png)|
|[wx.lib.agw.foldpanelbar.FoldPanelBar](https://docs.wxpython.org/wx.lib.agw.foldpanelbar.FoldPanelBar.html)|![](https://docs.wxpython.org/_static/images/widgets/fullsize/wxmsw/wx.lib.agw.foldpanelbar.foldpanelbar.png)|
|[wx.lib.agw.fourwaysplitter.FourWaySplitter](https://docs.wxpython.org/wx.lib.agw.fourwaysplitter.FourWaySplitter.html)|![](https://docs.wxpython.org/_static/images/widgets/fullsize/wxmsw/wx.lib.agw.fourwaysplitter.fourwaysplitter.png)|
|[wx.lib.agw.genericmessagedialog.GenericMessageDialog](https://docs.wxpython.org/wx.lib.agw.genericmessagedialog.GenericMessageDialog.html)|![](https://docs.wxpython.org/_static/images/widgets/fullsize/wxmsw/wx.lib.agw.genericmessagedialog.genericmessagedialog.png)|
|[wx.lib.agw.gradientbutton.GradientButton](https://docs.wxpython.org/wx.lib.agw.gradientbutton.GradientButton.html)|![](https://docs.wxpython.org/_static/images/widgets/fullsize/wxmsw/wx.lib.agw.gradientbutton.gradientbutton.png)|
|[wx.lib.agw.hyperlink.HyperLinkCtrl](https://docs.wxpython.org/wx.lib.agw.hyperlink.HyperLinkCtrl.html)|![](https://docs.wxpython.org/_static/images/widgets/fullsize/wxmsw/wx.lib.agw.hyperlink.hyperlinkctrl.png)|
|[wx.lib.agw.hypertreelist.HyperTreeList](https://docs.wxpython.org/wx.lib.agw.hypertreelist.HyperTreeList.html)|![](https://docs.wxpython.org/_static/images/widgets/fullsize/wxmsw/wx.lib.agw.hypertreelist.hypertreelist.png)|
|[wx.lib.agw.infobar.InfoBar](https://docs.wxpython.org/wx.lib.agw.infobar.InfoBar.html)|![](https://docs.wxpython.org/_static/images/widgets/fullsize/wxmsw/wx.lib.agw.infobar.infobar.png)|
|[wx.lib.agw.knobctrl.KnobCtrl](https://docs.wxpython.org/wx.lib.agw.knobctrl.KnobCtrl.html)|![](https://docs.wxpython.org/_static/images/widgets/fullsize/wxmsw/wx.lib.agw.knobctrl.knobctrl.png)|
|[wx.lib.agw.labelbook.FlatImageBook](https://docs.wxpython.org/wx.lib.agw.labelbook.FlatImageBook.html)|![](https://docs.wxpython.org/_static/images/widgets/fullsize/wxmsw/wx.lib.agw.labelbook.flatimagebook.png)|
|[wx.lib.agw.labelbook.LabelBook](https://docs.wxpython.org/wx.lib.agw.labelbook.LabelBook.html)|![](https://docs.wxpython.org/_static/images/widgets/fullsize/wxmsw/wx.lib.agw.labelbook.labelbook.png)|
|[wx.lib.agw.multidirdialog.MultiDirDialog](https://docs.wxpython.org/wx.lib.agw.multidirdialog.MultiDirDialog.html)|![](https://docs.wxpython.org/_static/images/widgets/fullsize/wxgtk/wx.lib.agw.multidirdialog.multidirdialog.png)|
|[wx.lib.agw.peakmeter.PeakMeterCtrl](https://docs.wxpython.org/wx.lib.agw.peakmeter.PeakMeterCtrl.html)|![](https://docs.wxpython.org/_static/images/widgets/fullsize/wxmsw/wx.lib.agw.peakmeter.peakmeterctrl.png)|
|[wx.lib.agw.piectrl.PieCtrl](https://docs.wxpython.org/wx.lib.agw.piectrl.PieCtrl.html)|![](https://docs.wxpython.org/_static/images/widgets/fullsize/wxgtk/wx.lib.agw.piectrl.piectrl.png)|
|[wx.lib.agw.piectrl.ProgressPie](https://docs.wxpython.org/wx.lib.agw.piectrl.ProgressPie.html)|![](https://docs.wxpython.org/_static/images/widgets/fullsize/wxmsw/wx.lib.agw.piectrl.progresspie.png)|
|[wx.lib.agw.pybusyinfo.PyBusyInfo](https://docs.wxpython.org/wx.lib.agw.pybusyinfo.PyBusyInfo.html)|![](https://docs.wxpython.org/_static/images/widgets/fullsize/wxgtk/wx.lib.agw.pybusyinfo.pybusyinfo.png)|
|[wx.lib.agw.pycollapsiblepane.PyCollapsiblePane](https://docs.wxpython.org/wx.lib.agw.pycollapsiblepane.PyCollapsiblePane.html)|![](https://docs.wxpython.org/_static/images/widgets/fullsize/wxgtk/wx.lib.agw.pycollapsiblepane.pycollapsiblepane.png)|
|[wx.lib.agw.pygauge.PyGauge](https://docs.wxpython.org/wx.lib.agw.pygauge.PyGauge.html)|![](https://docs.wxpython.org/_static/images/widgets/fullsize/wxmsw/wx.lib.agw.pygauge.pygauge.png)|
|[wx.lib.agw.pyprogress.PyProgress](https://docs.wxpython.org/wx.lib.agw.pyprogress.PyProgress.html)|![](https://docs.wxpython.org/_static/images/widgets/fullsize/wxgtk/wx.lib.agw.pyprogress.pyprogress.png)|
|[wx.lib.agw.ribbon.bar.RibbonBar](https://docs.wxpython.org/wx.lib.agw.ribbon.bar.RibbonBar.html)|![](https://docs.wxpython.org/_static/images/widgets/fullsize/wxgtk/wx.lib.agw.ribbon.bar.ribbonbar.png)|
|[wx.lib.agw.ribbon.buttonbar.RibbonButtonBar](https://docs.wxpython.org/wx.lib.agw.ribbon.buttonbar.RibbonButtonBar.html)|![](https://docs.wxpython.org/_static/images/widgets/fullsize/wxgtk/wx.lib.agw.ribbon.buttonbar.ribbonbuttonbar.png)|
|[wx.lib.agw.ribbon.gallery.RibbonGallery](https://docs.wxpython.org/wx.lib.agw.ribbon.gallery.RibbonGallery.html)|![](https://docs.wxpython.org/_static/images/widgets/fullsize/wxgtk/wx.lib.agw.ribbon.gallery.ribbongallery.png)|
|[wx.lib.agw.ribbon.page.RibbonPage](https://docs.wxpython.org/wx.lib.agw.ribbon.page.RibbonPage.html)|![](https://docs.wxpython.org/_static/images/widgets/fullsize/wxgtk/wx.lib.agw.ribbon.page.ribbonpage.png)|
|[wx.lib.agw.ribbon.panel.RibbonPanel](https://docs.wxpython.org/wx.lib.agw.ribbon.panel.RibbonPanel.html)|![](https://docs.wxpython.org/_static/images/widgets/fullsize/wxgtk/wx.lib.agw.ribbon.panel.ribbonpanel.png)|
|[wx.lib.agw.ribbon.toolbar.RibbonToolBar](https://docs.wxpython.org/wx.lib.agw.ribbon.toolbar.RibbonToolBar.html)|![](https://docs.wxpython.org/_static/images/widgets/fullsize/wxmsw/wx.lib.agw.ribbon.toolbar.ribbontoolbar.png)|
|[wx.lib.agw.rulerctrl.RulerCtrl](https://docs.wxpython.org/wx.lib.agw.rulerctrl.RulerCtrl.html)|![](https://docs.wxpython.org/_static/images/widgets/fullsize/wxgtk/wx.lib.agw.rulerctrl.rulerctrl.png)|
|[wx.lib.agw.shapedbutton.SBitmapButton](https://docs.wxpython.org/wx.lib.agw.shapedbutton.SBitmapButton.html)|![](https://docs.wxpython.org/_static/images/widgets/fullsize/wxgtk/wx.lib.agw.shapedbutton.sbitmapbutton.png)|
|[wx.lib.agw.shapedbutton.SBitmapTextButton](https://docs.wxpython.org/wx.lib.agw.shapedbutton.SBitmapTextButton.html)|![](https://docs.wxpython.org/_static/images/widgets/fullsize/wxgtk/wx.lib.agw.shapedbutton.sbitmaptextbutton.png)|
|[wx.lib.agw.shapedbutton.SBitmapTextToggleButton](https://docs.wxpython.org/wx.lib.agw.shapedbutton.SBitmapTextToggleButton.html)|![](https://docs.wxpython.org/_static/images/widgets/fullsize/wxgtk/wx.lib.agw.shapedbutton.sbitmaptexttogglebutton.png)|
|[wx.lib.agw.shapedbutton.SBitmapToggleButton](https://docs.wxpython.org/wx.lib.agw.shapedbutton.SBitmapToggleButton.html)|![](https://docs.wxpython.org/_static/images/widgets/fullsize/wxgtk/wx.lib.agw.shapedbutton.sbitmaptogglebutton.png)|
|[wx.lib.agw.shortcuteditor.ShortcutEditor](https://docs.wxpython.org/wx.lib.agw.shortcuteditor.ShortcutEditor.html)|![](https://docs.wxpython.org/_static/images/widgets/fullsize/wxgtk/wx.lib.agw.shortcuteditor.shortcuteditor.png)|
|[wx.lib.agw.speedmeter.SpeedMeter](https://docs.wxpython.org/wx.lib.agw.speedmeter.SpeedMeter.html)|![](https://docs.wxpython.org/_static/images/widgets/fullsize/wxgtk/wx.lib.agw.speedmeter.speedmeter.png)|
|[wx.lib.agw.supertooltip.SuperToolTip](https://docs.wxpython.org/wx.lib.agw.supertooltip.SuperToolTip.html)|![](https://docs.wxpython.org/_static/images/widgets/fullsize/wxgtk/wx.lib.agw.supertooltip.supertooltip.png)|
|[wx.lib.agw.thumbnailctrl.ThumbnailCtrl](https://docs.wxpython.org/wx.lib.agw.thumbnailctrl.ThumbnailCtrl.html)|![](https://docs.wxpython.org/_static/images/widgets/fullsize/wxmsw/wx.lib.agw.thumbnailctrl.thumbnailctrl.png)|
|[wx.lib.agw.toasterbox.ToasterBox](https://docs.wxpython.org/wx.lib.agw.toasterbox.ToasterBox.html)|![](https://docs.wxpython.org/_static/images/widgets/fullsize/wxmsw/wx.lib.agw.toasterbox.toasterbox.png)|
|[wx.lib.agw.ultimatelistctrl.UltimateListCtrl](https://docs.wxpython.org/wx.lib.agw.ultimatelistctrl.UltimateListCtrl.html)|![](https://docs.wxpython.org/_static/images/widgets/fullsize/wxmsw/wx.lib.agw.ultimatelistctrl.ultimatelistctrl.png)|
|[wx.lib.agw.xlsgrid.XLSGrid](https://docs.wxpython.org/wx.lib.agw.xlsgrid.XLSGrid.html)|![](https://docs.wxpython.org/_static/images/widgets/fullsize/wxmsw/wx.lib.agw.xlsgrid.xlsgrid.png)|
|[wx.lib.agw.zoombar.ZoomBar](https://docs.wxpython.org/wx.lib.agw.zoombar.ZoomBar.html)|![](https://docs.wxpython.org/_static/images/widgets/fullsize/wxmsw/wx.lib.agw.zoombar.zoombar.png)|
|[wx.Listbook](https://docs.wxpython.org/wx.Listbook.html)|![](https://docs.wxpython.org/_static/images/widgets/fullsize/wxmsw/wx.listbook.png)|
|[wx.ListBox](https://docs.wxpython.org/wx.ListBox.html)|![](https://docs.wxpython.org/_static/images/widgets/fullsize/wxmac/wx.listbox.png)|
|[wx.ListCtrl](https://docs.wxpython.org/wx.ListCtrl.html)|![](https://docs.wxpython.org/_static/images/widgets/fullsize/wxgtk/wx.listctrl.png)|
|[wx.ListView](https://docs.wxpython.org/wx.ListView.html)|![](https://docs.wxpython.org/_static/images/widgets/fullsize/wxgtk/wx.listview.png)|
|[wx.MiniFrame](https://docs.wxpython.org/wx.MiniFrame.html)|![](https://docs.wxpython.org/_static/images/widgets/fullsize/wxmsw/wx.miniframe.png)|
|[wx.Notebook](https://docs.wxpython.org/wx.Notebook.html)|![](https://docs.wxpython.org/_static/images/widgets/fullsize/wxgtk/wx.notebook.png)|
|[wx.RadioBox](https://docs.wxpython.org/wx.RadioBox.html)|![](https://docs.wxpython.org/_static/images/widgets/fullsize/wxmsw/wx.radiobox.png)|
|[wx.RadioButton](https://docs.wxpython.org/wx.RadioButton.html)|![](https://docs.wxpython.org/_static/images/widgets/fullsize/wxgtk/wx.radiobutton.png)|
|[wx.ScrollBar](https://docs.wxpython.org/wx.ScrollBar.html)|![](https://docs.wxpython.org/_static/images/widgets/fullsize/wxmac/wx.scrollbar.png)|
|[wx.SearchCtrl](https://docs.wxpython.org/wx.SearchCtrl.html)|![](https://docs.wxpython.org/_static/images/widgets/fullsize/wxgtk/wx.searchctrl.png)|
|[wx.Slider](https://docs.wxpython.org/wx.Slider.html)|![](https://docs.wxpython.org/_static/images/widgets/fullsize/wxmsw/wx.slider.png)|
|[wx.SpinButton](https://docs.wxpython.org/wx.SpinButton.html)|![](https://docs.wxpython.org/_static/images/widgets/fullsize/wxmac/wx.spinbutton.png)|
|[wx.SpinCtrl](https://docs.wxpython.org/wx.SpinCtrl.html)|![](https://docs.wxpython.org/_static/images/widgets/fullsize/wxgtk/wx.spinctrl.png)|
|[wx.SpinCtrlDouble](https://docs.wxpython.org/wx.SpinCtrlDouble.html)|![](https://docs.wxpython.org/_static/images/widgets/fullsize/wxmac/wx.spinctrldouble.png)|
|[wx.StaticBitmap](https://docs.wxpython.org/wx.StaticBitmap.html)|![](https://docs.wxpython.org/_static/images/widgets/fullsize/wxgtk/wx.staticbitmap.png)|
|[wx.StaticBox](https://docs.wxpython.org/wx.StaticBox.html)|![](https://docs.wxpython.org/_static/images/widgets/fullsize/wxmsw/wx.staticbox.png)|
|[wx.StaticText](https://docs.wxpython.org/wx.StaticText.html)|![](https://docs.wxpython.org/_static/images/widgets/fullsize/wxmsw/wx.statictext.png)|
|[wx.TextCtrl](https://docs.wxpython.org/wx.TextCtrl.html)|![](https://docs.wxpython.org/_static/images/widgets/fullsize/wxgtk/wx.textctrl.png)|
|[wx.ToggleButton](https://docs.wxpython.org/wx.ToggleButton.html)|![](https://docs.wxpython.org/_static/images/widgets/fullsize/wxgtk/wx.togglebutton.png)|
|[wx.TreeCtrl](https://docs.wxpython.org/wx.TreeCtrl.html)|![](https://docs.wxpython.org/_static/images/widgets/fullsize/wxmac/wx.treectrl.png)|